name: Auto Assign
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const reviewers = ['mariocuomo', 'adminSecCop'];
            const reviewer = reviewers[Math.floor(Math.random() * reviewers.length)];
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [reviewer]
            });
