name: Assign Reviewer

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Assign reviewer
      uses: actions/github-script@v6
      with:
        script: |
          const reviewers = ['mariocuomo', 'adminSecCop'];
          const reviewer = reviewers[Math.floor(Math.random() * reviewers.length)];
          github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: [reviewer]
          });

  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Debug context
      run: echo "${{ toJson(github.event) }}"

    - name: Add label based on comment
      uses: actions/github-script@v6
      with:
        script: |
          const description = context.payload.pull_request.body;
          const firstLine = comment.split('\n')[0];
          const match = firstLine.match(/^PULL REQUEST TYPE: \s*(.*)$/i);
          if (match) {
            const pullRequestType = match[1].trim().toLowerCase();
            let label;
            switch (pullRequestType) {
              case 'feature':
                label = 'feature';
                break;
              case 'bugfix':
                label = 'bug';
                break;
              case 'documentation':
                label = 'documentation';
                break;
              default:
                label = 'other';
            }
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: [label]
            });
          }

